keycloak:
  client_id: 'CLIENT_ID'
  client_secret: 'CLIENT_SECRET'
  issuer: 'https://example.com/'
  realm: 'REALM_NAME'

proxy:
  host: 'http://localhost:3100'

server:
  port: 3100
  session_id: 'keycloak-proxy'